import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import axios from "axios";
import ThemeToggle from "../components/ThemeToggle";
import { useTheme } from "../contexts/ThemeContext";

export default function Analytics() {
  const { sub_handle: rawHandle } = useLocalSearchParams();
  const handle = Array.isArray(rawHandle) ? rawHandle[0] : rawHandle || "wasif1607";
  const router = useRouter(); const { colors } = useTheme(); const { width } = useWindowDimensions();
  const [submissions, setSubmissions] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(null);
  const fetchData = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); setError(null); try { const response = await axios.get(`https://codeforces.com/api/user.status?handle=${encodeURIComponent(handle)}&from=1&count=350`); if (response.data.status !== "OK") throw new Error(); setSubmissions(response.data.result); } catch { setError("Analytics are unavailable right now. Check your connection and try again."); } finally { setLoading(false); setRefreshing(false); } }, [handle]);
  useEffect(() => { fetchData(); }, [fetchData]);
  const analytics = useMemo(() => calculateAnalytics(submissions), [submissions]);

  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}>
    <View style={[styles.nav, { borderBottomColor: colors.border }]}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.surfaceAlt }]}><Text style={[styles.backText, { color: colors.text }]}>‹</Text></Pressable><Text style={[styles.navTitle, { color: colors.text }]}>Analytics</Text><ThemeToggle /></View>
    {loading ? <ActivityIndicator size="large" color={colors.primary} style={{ flex: 1 }} /> : error ? <View style={styles.center}><Text style={styles.errorIcon}>!</Text><Text style={[styles.heading, { color: colors.text }]}>Couldn’t load analytics</Text><Text style={[styles.description, { color: colors.muted }]}>{error}</Text><Pressable onPress={() => fetchData()} style={[styles.retry, { backgroundColor: colors.primary }]}><Text style={{ color: "#fff", fontWeight: "800" }}>Try again</Text></Pressable></View> :
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => fetchData(true)} colors={[colors.primary]} tintColor={colors.primary} />}>
      <Text style={[styles.eyebrow, { color: colors.primary }]}>LAST 7 DAYS · @{handle}</Text><Text style={[styles.title, { color: colors.text }]}>Your performance</Text><Text style={[styles.description, { color: colors.muted }]}>A simple view of consistency and submission accuracy.</Text>
      <View style={styles.summary}><Metric label="Accepted" value={analytics.accepted} color={colors.success} colors={colors} /><Metric label="Daily avg" value={analytics.average.toFixed(1)} color={colors.primary} colors={colors} /><Metric label="Best day" value={analytics.maximum} color="#d97706" colors={colors} /></View>
      <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.heading, { color: colors.text }]}>Accepted by day</Text><Text style={[styles.caption, { color: colors.muted }]}>Consistency over the past week</Text><View style={styles.chart}>{analytics.days.map((day) => <View key={day.label} style={styles.barColumn}><Text style={[styles.barValue, { color: colors.text }]}>{day.count}</Text><View style={[styles.barTrack, { backgroundColor: colors.surfaceAlt, height: 130 }]}><View style={{ width: "100%", minHeight: day.count ? 8 : 0, height: `${day.count / Math.max(analytics.maximum, 1) * 100}%`, borderRadius: 8, backgroundColor: colors.primary }} /></View><Text style={[styles.barLabel, { color: colors.muted }]}>{day.label}</Text></View>)}</View></View>
      <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.accuracyTop}><View><Text style={[styles.heading, { color: colors.text }]}>Accuracy</Text><Text style={[styles.caption, { color: colors.muted }]}>Decisive verdicts this week</Text></View><Text style={[styles.accuracy, { color: colors.primary }]}>{Math.round(analytics.accuracy * 100)}%</Text></View><View style={[styles.accuracyTrack, { backgroundColor: colors.surfaceAlt }]}><View style={{ height: "100%", width: `${analytics.accuracy * 100}%`, backgroundColor: colors.primary, borderRadius: 6 }} /></View><View style={styles.verdicts}><Verdict label="Accepted" value={analytics.verdicts.OK} color={colors.success} /><Verdict label="Wrong answer" value={analytics.verdicts.WRONG_ANSWER} color={colors.danger} /><Verdict label="Time limit" value={analytics.verdicts.TIME_LIMIT_EXCEEDED} color="#d97706" /></View></View>
    </ScrollView>}
  </SafeAreaView>;
}

function calculateAnalytics(items) { const now = new Date(); const days = Array.from({ length: 7 }, (_, i) => { const date = new Date(now); date.setDate(now.getDate() - (6 - i)); return { date: date.toDateString(), label: date.toLocaleDateString(undefined, { weekday: "short" }), count: 0 }; }); const verdicts = { OK: 0, WRONG_ANSWER: 0, TIME_LIMIT_EXCEEDED: 0 }; items.forEach((item) => { const day = days.find((entry) => entry.date === new Date(item.creationTimeSeconds * 1000).toDateString()); if (!day) return; if (item.verdict === "OK") day.count += 1; if (Object.hasOwn(verdicts, item.verdict)) verdicts[item.verdict] += 1; }); const accepted = days.reduce((sum, day) => sum + day.count, 0); const decisive = Object.values(verdicts).reduce((a, b) => a + b, 0); return { days, verdicts, accepted, average: accepted / 7, maximum: Math.max(...days.map((day) => day.count)), accuracy: decisive ? verdicts.OK / decisive : 0 }; }
function Metric({ label, value, color, colors }) { return <View style={[styles.metric, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color, fontSize: 23, fontWeight: "850" }}>{value}</Text><Text style={{ color: colors.muted, fontSize: 10 }}>{label}</Text></View>; }
function Verdict({ label, value = 0, color }) { return <View style={styles.verdict}><View style={[styles.dot, { backgroundColor: color }]} /><Text style={{ flex: 1, color, fontWeight: "700" }}>{label}</Text><Text style={{ color, fontWeight: "850" }}>{value}</Text></View>; }

const styles = StyleSheet.create({ safe: { flex: 1 }, nav: { minHeight: 62, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth }, back: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, backText: { fontSize: 35, lineHeight: 37 }, navTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "800" }, content: { padding: 16, paddingBottom: 45, gap: 14 }, eyebrow: { fontSize: 10, fontWeight: "850", letterSpacing: 1.4, marginTop: 7 }, title: { fontSize: 29, fontWeight: "850", letterSpacing: -0.7 }, description: { fontSize: 13, lineHeight: 20 }, summary: { flexDirection: "row", gap: 8 }, metric: { flex: 1, minHeight: 79, borderWidth: 1, borderRadius: 17, alignItems: "center", justifyContent: "center", gap: 3 }, card: { borderWidth: 1, borderRadius: 21, padding: 17 }, heading: { fontSize: 18, fontWeight: "850" }, caption: { fontSize: 11, marginTop: 3 }, chart: { height: 182, flexDirection: "row", alignItems: "flex-end", gap: 8, marginTop: 16 }, barColumn: { flex: 1, height: "100%", alignItems: "center", justifyContent: "flex-end" }, barValue: { fontSize: 10, fontWeight: "750", marginBottom: 4 }, barTrack: { width: "78%", borderRadius: 8, overflow: "hidden", justifyContent: "flex-end" }, barLabel: { fontSize: 9, marginTop: 6 }, accuracyTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, accuracy: { fontSize: 28, fontWeight: "850" }, accuracyTrack: { height: 9, borderRadius: 6, overflow: "hidden", marginVertical: 18 }, verdicts: { gap: 11 }, verdict: { flexDirection: "row", alignItems: "center", gap: 9 }, dot: { width: 8, height: 8, borderRadius: 4 }, center: { flex: 1, padding: 30, alignItems: "center", justifyContent: "center" }, errorIcon: { color: "#fff", backgroundColor: "#dc2626", width: 48, height: 48, borderRadius: 16, textAlign: "center", textAlignVertical: "center", fontSize: 28, fontWeight: "800", overflow: "hidden", marginBottom: 14 }, retry: { borderRadius: 13, paddingHorizontal: 20, paddingVertical: 12, marginTop: 16 } });
